### ISSUE TITLE
Rename to Unified ASAT Visualizer

### ISSUE THREAD

**Issue by Inventitech** [ClintonCao/UnifiedASATVisualizer#129]
In the first dialog, tool still says Blueturtle Visualizer. That's fine, but maybe at least change to Unified ASAT Visualizer?

**Comment by ClintonCao** [comment]
Ah right, I'll change the name.

**Comment by Inventitech** [comment]
Perhaps it is also necessary to reflect this name change in the repository name, and throughout README?

**Comment by ClintonCao** [comment]
I think that would be a good idea.

**Comment by ClintonCao** [comment]
Repo name is changed to UnifiedASATVisualizer. 
Name in README is changed in #124.
Title of Java Application is also changed in #124
