### ISSUE TITLE
Provide a downloadable package

### ISSUE THREAD

**Issue by mauricioaniche** [ClintonCao/UnifiedASATVisualizer#137]
There's no package for download. Currently, I need to build the tool to play with it. Suggestion: in _releases_, provide a .zip file with the product.

**Comment by Inventitech** [comment]
Hey guys, I'd actually suggest we package this on the tool's website instead of putting the binary in this repository. @ClintonCao, could you do that?

**Comment by Inventitech** [comment]
Actually, @ClintonCao, I just provided you with a pull request to do just that :-)

**Comment by ClintonCao** [comment]
@Inventitech Yes, I've merged it :)

**Comment by Inventitech** [comment]
@ClintonCao Thx!

@mauricioaniche See https://clintoncao.github.io/uav/

**Comment by Inventitech** [comment]
New downloadable release includes hot fix for small screens: https://github.com/ClintonCao/uav/pull/2

**Comment by Inventitech** [comment]
@mauricioaniche Think this can be closed now?
