### ISSUE TITLE
Visualization issue in a Mac 13' inches

### ISSUE THREAD

**Issue by mauricioaniche** [ClintonCao/UnifiedASATVisualizer#141]
In my mac 13' inches, I cannot see the full page. The right part doesn't show the 'other' menu. If I zoom out, that works.

You can see it at http://imgur.com/XhZtlA3.

**Comment by Inventitech** [comment]
Also, the right part is not zoomable.

**Comment by boninggong** [comment]
See the commit 9cb6e7c for the changes that should fix this problem.

**Comment by mauricioaniche** [comment]
Works on my machine now: http://imgur.com/a/9vXsd

Thanks!

**Comment by mauricioaniche** [comment]
Oh, the examples in the website need to be updated too! :)

**Comment by ClintonCao** [comment]
Yes I would need to add in the fix on the website.

**Comment by Inventitech** [comment]
Fix is on website.

**Comment by ClintonCao** [comment]
Yes I've already updated it on the website repo.

**Comment by mauricioaniche** [comment]
Just tested and it works now!
